version: '3.6'

services:
  server:
    image: registry.digitalocean.com/autoshack/shack:server
    env_file:
      - ./shackServer/.env
    expose:
      - '1783'
    ports:
      - '1783:1783'
    command: yarn start
    networks:
      - shack

  web:
    depends_on:
      - server
    image: registry.digitalocean.com/autoshack/shack:web
    environment: 
      - Port=4200
    expose:
      - '80'
    ports:
      - '80:80'
    networks:
      - shack

networks:
  shack:
    name: shack