name: Run Cypress Tests

on:
  pull_request:
    branches:
      - "*" # This will trigger the workflow for all branches

jobs:
  cypress-tests:
    runs-on: [self-hosted, linux] # Only runs on self

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Change this to your desired Node.js version

      - name: Install yarn
        run: npm install -g yarn

      - name: Install Cypress dependencies
        run: apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y

      - name: Install web dependencies
        run: |
          cd shackweb2
          yarn install

      - name: Start React application
        run: |
          cd shackweb2
          yarn start &
          sleep 10  # Give some time for the React application to start

      - name: Run Cypress tests
        run: |
          cd shackweb2
          yarn cypress run --record --key b19bca40-c361-4bf7-9f25-1efd583c503b --env branch_name=${{ github.event.pull_request.head.ref }}

      - name: Clean up
        if: always()
        run: |
          npm uninstall -g yarn
          pkill -f "yarn start"
