name: Run Cypress Tests

on:
  pull_request:
    branches:
      - "*"  # This will trigger the workflow for all branches

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Change this to your desired Node.js version

      - name: Install dependencies
        run: |
          cd shackServer
          yarn install
          yarn build
          cd ../shackweb2
          yarn install

      - name: Start Node.js server
        run: |
          cd shackServer
          PORT=1783
          yarn start &
          sleep 10  # Give some time for the server to start

      - name: Start React application
        run: |
          cd shackweb2
          yarn start &
          sleep 10  # Give some time for the React application to start

      - name: Run Cypress tests
        run: |
          cd shackweb2
          yarn cypress run --record --key b19bca40-c361-4bf7-9f25-1efd583c503b --env branch_name=${{ github.event.pull_request.head.ref }}
