name: Run Cypress Tests

on:
  pull_request:
    branches:
      - "*" # This will trigger the workflow for all branches when they create a PR
  push:
    branches:
      - main # This will trigger the workflow for any push to the main branch

jobs:
  cypress-tests:
    runs-on: [self-hosted, linux] # Only runs on self

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: shackweb2/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('shackweb2/yarn.lock') }}

      - name: Install Cypress dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - name: Install web dependencies
        run: |
          cd shackweb2
          yarn install

      - name: Start React application
        run: |
          cd shackweb2
          yarn start &
          sleep 10  # Give some time for the React application to start

      - name: Run Cypress tests
        run: |
          cd shackweb2
          yarn cypress run --record --key b19bca40-c361-4bf7-9f25-1efd583c503b --env branch_name=${{ github.event.pull_request.head.ref }}

      - name: Clean up
        if: always()
        run: |
          if command -v yarn; then
            npm uninstall -g yarn
          fi
          pkill -f "yarn start"
