name: Run Cypress Tests

on:
  pull_request:
    branches:
      - "*" # This will trigger the workflow for all branches when they create a PR
  push:
    branches:
      - main # This will trigger the workflow for any push to the main branch

jobs:
  cypress-tests:
    runs-on: [self-hosted, linux] # Only runs on self
    defaults:
      run:
        working-directory: shackWeb # Set default working directory for all steps

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Cypress dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - name: Install dependencies
        run: yarn install
        working-directory: shackWeb # Specify working directory for this step

      - name: Start React application
        run: |
          yarn start &
          sleep 10  # Give some time for the React application to start
        working-directory: shackWeb # Specify working directory for this step

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: yarn start
          wait-on: 'http://localhost:3000'
          record: true
          parallel: true
          group: 'Cypress tests'
          browser: chrome
          env: branch_name=${{ github.event.pull_request.head.ref }}

      - name: Clean up
        if: always()
        run: |
          if command -v yarn; then
            npm uninstall -g yarn
          fi
          pkill -f "yarn start"
