name: Run Cypress Tests and Trigger Docker Image CI on push to main

on:
  pull_request:
    branches:
      - "*" # This will trigger the workflow for all branches when they create a PR
  push:
    branches:
      - main # This will trigger the workflow for any push to the main branch
  workflow_dispatch:

jobs:
  cypress-tests:
    runs-on: [self-hosted, linux] # Only runs on self

    outputs:
      test-result: ${{ steps.run-cypress.outputs.test-result }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install yarn
        run: npm install -g yarn

      - name: Install Cypress dependencies
        run: apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y

      - name: Install web dependencies
        run: |
          cd shackweb2
          yarn install

      - name: Start React application
        run: |
          cd shackweb2
          yarn start &
          sleep 10  # Give some time for the React application to start

      - name: Run Cypress tests
        id: run-cypress
        run: |
          cd shackweb2
          yarn cypress run --record --key b19bca40-c361-4bf7-9f25-1efd583c503b --env branch_name=${{ github.event.pull_request.head.ref }}
          echo "::set-output name=test-result::$?"

      - name: Build the Web Docker image
        if: steps.run-cypress.outputs.test-result == '0'
        run: |
          cd shackweb2
          docker build . --file Dockerfile --tag localhost/autoshack/shack_web

      - name: Build the Server Docker image
        if: steps.run-cypress.outputs.test-result == '0'
        run: |
          cd shackServer
          docker build . --file Dockerfile --tag localhost/autoshack/shack_server

      - name: Push the Docker images to registry
        if: steps.run-cypress.outputs.test-result == '0'
        run: |
          docker push localhost/autoshack/shack_server
          docker push localhost/autoshack/shack_web
